# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: maxSlimer
author: 0xsol
# logo: logo.png

# # Define the output directory for the build
#build:
#  path_output: ./docs

exclude_patterns:
  - _build


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # execute_notebooks: force
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


# Information about where the book exists on the web
repository:
  url: https://github.com/SOLEROM/maxSlimer  # Online location of your book
  path_to_book: root  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

html_theme_options:
  color_theme: "dark" 
